version: '3.8'
services:

  guacamole:
    image: unsafetypin/guacamole
    container_name: guacamole
    restart: unless-stopped
    environment:
    - EXTENSIONS=auth-totp
    volumes:
    - ./config:/config
    # ports:
    # - "8080:8080"
  
  ngnix-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
